"""create base

Revision ID: 91e511dbd8b7
Revises: 
Create Date: 2023-03-19 20:34:40.009124

"""
from alembic import op
from src.core.settings import settings
from src.services.authorization import hash_password
from datetime import datetime
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e511dbd8b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hashed', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(users,
                   [
                       {
                           'id': 1,
                           'username': settings.admin_username,
                           'password_hashed': hash_password(settings.admin_password),
                           'role': 'admin',
                           'created_at': datetime.now(),
                       }
                   ])
    op.create_table('methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.Enum('dataProcessing', 'fit', 'predict', 'download', name='methods_enum'), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_methods_user_id'), 'methods', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_methods_user_id'), table_name='methods')
    op.drop_table('methods')
    op.drop_table('users')
    # ### end Alembic commands ###
